/**
 * google.js — Arctic provider wrapper for Google OAuth 2.0
 *
 * Uses PKCE (required by Google). Returns id_token which contains
 * sub (providerUserId) and email.
 *
 * Config: { clientId, clientSecret, redirectUri }
 */
import { Google, generateState, generateCodeVerifier, decodeIdToken } from 'arctic';
import { ProviderError } from '../errors.js';

export const PROVIDER_NAME = 'google';

export default class GoogleProvider {
  constructor(config) {
    this._client = new Google(config.clientId, config.clientSecret, config.redirectUri);
  }

  /**
   * Generate the authorization URL.
   * @param {string} state
   * @param {string} codeVerifier — must be generated by caller (generateCodeVerifier())
   * @returns {URL}
   */
  createAuthorizationURL(state, codeVerifier) {
    return this._client.createAuthorizationURL(state, codeVerifier, ['openid', 'email', 'profile']);
  }

  /**
   * Exchange authorization code for tokens and extract user identity.
   * @param {string} code
   * @param {string} codeVerifier
   * @returns {Promise<{ providerUserId: string, email: string }>}
   */
  async validateCallback(code, codeVerifier) {
    let tokens;
    try {
      tokens = await this._client.validateAuthorizationCode(code, codeVerifier);
    } catch (err) {
      throw new ProviderError(PROVIDER_NAME, `Token exchange failed: ${err.message}`);
    }

    let claims;
    try {
      claims = decodeIdToken(tokens.idToken());
    } catch (err) {
      throw new ProviderError(PROVIDER_NAME, `Failed to decode id_token: ${err.message}`);
    }

    return {
      providerUserId: String(claims.sub),
      email: typeof claims.email === 'string' ? claims.email : null,
    };
  }
}

export { generateState, generateCodeVerifier };
